version: "3.8"
services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL}
    volumes:
      - .:/app